### ISSUE TITLE
Add Used by section to README

### ISSUE THREAD

**Issue by bancek** [madron/iptables-exporter#1]
This project does not have a lot of stars but it would be nice for newcomers to see that it is production-ready.

[OpenAI is using it](https://openai.com/blog/scaling-kubernetes-to-7500-nodes/) which might be nice to add to README.

**Comment by madron** [comment]
I developed this project for internal use only and I didn't know someone else was using it.
Thanks for letting me know !

Moreover I use iptables-exporter only for a few hundreds of "pre-Kubernetes" servers and your blog
gave me some interesting ideas for Kubernetes nodes. ;-)
